In [ ]:
# Задание 1 Создайте numpy array с элементами от числа N до 0 
# (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [56]:
import numpy as np
n = 10
x = np.arange( 0, n )
rev_x = x[::-1]
rev_x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# Задание 2 Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [118]:
n = 5
a = np.diag(np.arange(n), k=0)
b = np.flip(a,1)
c = np.flip(b,0)
print(c)
c.sum()

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


10

In [ ]:
# Задание 3 Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
# Определите какому фильму было выставлено больше всего оценок 5.0.

In [54]:
import pandas as pd

# используется MovieLens 20M Dataset

data = pd.read_csv('ratings.csv')
data2 = pd.read_csv('movies.csv')

filter_5 = data [ ( (data['rating']== 5 ) ) ]
find_winer = filter_5['movieId'].value_counts().keys()[0]
winer = data2[ (data2['movieId']== find_winer) ]
winer

movieId                             title       genres
315      318  Shawshank Redemption, The (1994)  Crime|Drama

In [ ]:
# Задание 4 По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония)
# категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [ ]:
import pandas as pd
data = pd.read_csv('power.csv')

filter_country = data [ ( (data['country']=='Latvia') | (data['country']=='Estonia') | (data['country']=='Litva') ) ]

filter_category = filter_country [ ( (data['category']== 4) | (data['category']== 12) | (data['category']== 21) ) ]

filter_year = filter_category [ ( (data['year']>= 2005) & (data['year']<= 2019) ) ]

filter_quantity = filter_year [ ( (data['quantity']>= 0) ) ]

filter_sum = filter_quantity['quantity'].sum()

filter_sum

In [ ]:
# Задание 5 Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [124]:
import numpy as np
from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

x = linalg.solve(a, b)

np.allclose(np.dot(a, x), b)

True